# Generated by Django 6.0 on 2026-01-24 17:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delegate_controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
                ('previous_timestamp', models.IntegerField(blank=True, default=None, null=True)),
                ('previous_returncode', models.IntegerField(blank=True, default=None, null=True)),
                ('previous_message', models.TextField(blank=True, default=None, null=True)),
                ('last_change', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'delegate_control',
                'verbose_name_plural': 'delegate_controls',
                'db_table': 'delegate_controls',
                'ordering': ['-timestamp', 'host', 'command_name'],
            },
        ),
        migrations.CreateModel(
            name='delegate_errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'delegate_error',
                'verbose_name_plural': 'delegate_errors',
                'db_table': 'delegate_errors',
                'ordering': ['-timestamp', 'host', 'command_name'],
            },
        ),
        migrations.CreateModel(
            name='hosts_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16, unique=True)),
                ('ip', models.CharField(max_length=39)),
                ('valid_ips', models.CharField(default='127.0.0.1', max_length=130)),
                ('previous_ip', models.CharField(blank=True, max_length=39, null=True)),
                ('last_time_seen', models.IntegerField(blank=True, default=main.models._aux_get_now_utc_timestamp)),
                ('previous_last_time_seen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'host_registry',
                'verbose_name_plural': 'hosts_registry',
                'db_table': 'hosts_registry',
                'ordering': ['-last_time_seen', 'host'],
            },
        ),
        migrations.CreateModel(
            name='master_controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
                ('previous_timestamp', models.IntegerField(blank=True, default=None, null=True)),
                ('previous_returncode', models.IntegerField(blank=True, default=None, null=True)),
                ('previous_message', models.TextField(blank=True, default=None, null=True)),
                ('last_change', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'master_control',
                'verbose_name_plural': 'master_controls',
                'db_table': 'master_controls',
                'ordering': ['-timestamp', 'host', 'command_name'],
            },
        ),
        migrations.CreateModel(
            name='master_errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'master_error',
                'verbose_name_plural': 'master_errors',
                'db_table': 'master_errors',
                'ordering': ['-timestamp', 'host', 'command_name'],
            },
        ),
    ]
