# Generated by Django 6.0 on 2025-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delegate_controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'delegate_controls',
            },
        ),
        migrations.CreateModel(
            name='delegate_errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'delegate_errors',
            },
        ),
        migrations.CreateModel(
            name='hosts_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=39)),
                ('previous_ip', models.CharField(max_length=39)),
                ('last_updated', models.IntegerField()),
                ('previous_last_updated', models.IntegerField()),
            ],
            options={
                'db_table': 'hosts_registry',
            },
        ),
        migrations.CreateModel(
            name='master_controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'master_controls',
            },
        ),
        migrations.CreateModel(
            name='master_errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
                ('command_name', models.CharField(max_length=25)),
                ('returncode', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'master_errors',
            },
        ),
    ]
