#!/bin/bash

#Get service
if [ ! -z "$1" ]
then
    SERVICE="$1"
else
    echo "ERROR: Must supply what service to check"
    exit 3
fi
result=$(systemctl is-active $SERVICE)
if [ $result == "active" ]; then
    echo "Service is active"
    exit 0
else
    echo "Service is inactive"
    exit 1
fi