#!/bin/bash

#Get container
if [ ! -z "$1" ]
then
    CONTAINER="$1"
else
    echo "ERROR: Must supply what container to check"
    exit 1
fi

running=$(docker inspect --format='{{ .State.Running }}' $CONTAINER  2> /dev/null)
if [ $? -eq 1 ]; then
    echo "WARNING: Container not running"
    exit 0
fi

#available_cores=$(docker info | grep CPUs | aws '{print $2}')

cpu_usage="$(docker stats --no-stream $CONTAINER | grep -A1 CONTAINER | grep -v CONTAINER | awk '{print $3}')"

echo $cpu_usage