#!/bin/bash

#Get threshold passed as argument to script, if not keep it at 80%
if [ ! -z "$1" ]
then
    DISK="$1"
else
    echo "ERROR: Must supply what partition  to check"
    exit 1
fi

disk_usage=$(df $DISK | awk 'NR==2 {print $5}'| sed 's/%//' )

#echo $disk_usage

THRESHOLD=90
if (( $(echo "$disk_usage > $THRESHOLD" | bc -l) ));
then
    echo "CRITICAL: Filesystem $DISK usage is at ${disk_usage}%"
    exit 0
else
    echo "OK - Filesystem $DISK $disk_usage%"
    exit 0
fi